services:
  db:
    image: pgvector/pgvector:pg16
    # restart: always
    container_name: postgres_dj
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
