services:
  db:
    image: pgvector/pgvector:pg16
    # restart: always
    container_name: pg-vector
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  #your main app config goes here for testing an e2e service
  app:
    image: nginx
    container_name: app
    ports:
      - 8080:8080
    environment:
      - OPENAI_API_KEY
    networks:
      - hello-dapr

  app-dapr:
    image: "daprio/daprd:edge"
    container_name: app-dapr
    command: ["./daprd",
      "-app-id", "app-dapr",
      "--app-protocol", "http"]
    depends_on:
      - app
    network_mode: "service:app"

  kitchenai:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.dev
    container_name: kitchenai
    environment:
      - OPENAI_API_KEY
    ports:
      - 8000:8000
    networks:
      - hello-dapr
  
  kitchenai-dapr:
    image: "daprio/daprd:edge"
    container_name: kitchenai-dapr
    command: ["./daprd",
      "-app-id", "kitchenai",
      "--app-port", "8000",
      "--app-protocol", "http"]
    depends_on:
      - kitchenai
    network_mode: "service:kitchenai"

volumes:
  db:
    driver: local

networks:
  hello-dapr: