services:

  kitchenai:
    image: s6
    container_name: kitchenai-s6
    environment:
      - OPENAI_API_KEY
    ports:
      - 3501:3501
      - 3500:3500
      - 8000:8000

networks:
  hello-dapr: