services:

  client:
    build:
      context: ../
      dockerfile: docker/Dockerfile.client
    ports:
      - 8001:8000

  kitchenai:
    image: s6
    environment:
      - OPENAI_API_KEY
    ports:
      - 3501:3501
      - 3500:3500
      - 8000:8000
 