services:

  client:
    image: kitchen-client
    ports:
      - 8001:8000
    networks:
      - hello-dapr
      
  kitchenai:
    image: s6
    environment:
      - OPENAI_API_KEY
    ports:
      - 3501:3501
      - 3500:3500
      - 8000:8000
    networks:
      - hello-dapr
networks:
  hello-dapr: